import 'controller/parent_profile_controller.dart';import 'package:flutter/material.dart';import 'package:thamal_s_application7/core/app_export.dart';import 'package:thamal_s_application7/widgets/app_bar/appbar_leading_image.dart';import 'package:thamal_s_application7/widgets/app_bar/custom_app_bar.dart';class ParentProfileScreen extends GetWidget<ParentProfileController> {const ParentProfileScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 15.v), child: Column(children: [SizedBox(height: 16.v), Text("lbl_profile".tr, style: theme.textTheme.titleLarge), SizedBox(height: 28.v), Container(width: 116.h, margin: EdgeInsets.symmetric(horizontal: 108.h), padding: EdgeInsets.symmetric(horizontal: 21.h, vertical: 10.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder58), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 21.v), CustomImageView(imagePath: ImageConstant.imgSettingsBlue800, height: 53.adaptSize, width: 53.adaptSize), SizedBox(height: 6.v), CustomImageView(imagePath: ImageConstant.imgCamera, height: 15.adaptSize, width: 15.adaptSize, alignment: Alignment.centerRight)])), SizedBox(height: 50.v), _buildNameRow(), SizedBox(height: 13.v), _buildNicRow(), SizedBox(height: 13.v), _buildEmailRow(), SizedBox(height: 14.v), _buildMobileRow(), SizedBox(height: 14.v), _buildHomePhoneRow(), SizedBox(height: 13.v), _buildDateOfBirthRow(), SizedBox(height: 13.v), _buildAddressRow(), SizedBox(height: 12.v), _buildDistrictRow(), SizedBox(height: 11.v), _buildProvinceRow(), SizedBox(height: 29.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 6.h), child: Text("lbl_student_details2".tr, style: CustomTextStyles.bodySmall12))), SizedBox(height: 20.v), _buildStudentNameRow(), SizedBox(height: 13.v), _buildUmisIdRow(), SizedBox(height: 13.v), _buildUmisEmailRow(), SizedBox(height: 15.v), _buildRelationshipRow(), SizedBox(height: 12.v), _buildParentMobileRow(), SizedBox(height: 14.v), _buildParentHomePhoneRow()])), bottomNavigationBar: _buildLockRow())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 38.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgMegaphone, margin: EdgeInsets.only(left: 20.h, top: 22.v, bottom: 22.v)), actions: [Container(height: 40.adaptSize, width: 40.adaptSize, margin: EdgeInsets.symmetric(horizontal: 10.h, vertical: 8.v), decoration: BoxDecoration(color: appTheme.blueGray100, borderRadius: BorderRadius.circular(20.h)))]); } 
/// Section Widget
Widget _buildNameRow() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_name".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 64.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildNicRow() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_nic".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 74.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildEmailRow() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_email".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 66.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildMobileRow() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_mobile".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 61.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildHomePhoneRow() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_home_phone".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 31.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildDateOfBirthRow() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_date_of_birth".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 31.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildAddressRow() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_address".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 55.h, bottom: 2.v), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildDistrictRow() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_district".tr, style: theme.textTheme.bodySmall)), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 58.h, bottom: 3.v), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildProvinceRow() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Text("lbl_province".tr, style: theme.textTheme.bodySmall)), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 51.h, bottom: 4.v), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildStudentNameRow() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_name2".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 64.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildUmisIdRow() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_umis_id".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 51.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildUmisEmailRow() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_umis_email".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 31.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildRelationshipRow() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_relationship".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 33.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildParentMobileRow() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_mobile".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 61.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildParentHomePhoneRow() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_home_phone".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 31.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildLockRow() { return Padding(padding: EdgeInsets.only(left: 12.h, right: 12.h, bottom: 10.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgLock, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 2.v, bottom: 6.v)), CustomImageView(imagePath: ImageConstant.imgBellRing, height: 24.adaptSize, width: 24.adaptSize), CustomImageView(imagePath: ImageConstant.imgHome, height: 17.v, width: 20.h, margin: EdgeInsets.only(top: 2.v, bottom: 5.v), onTap: () {onTapImgHome();}), CustomImageView(imagePath: ImageConstant.imgBus, height: 24.adaptSize, width: 24.adaptSize, onTap: () {onTapImgBus();}), CustomImageView(imagePath: ImageConstant.imgFacebook, height: 18.v, width: 22.h, margin: EdgeInsets.only(top: 2.v, bottom: 3.v), onTap: () {onTapImgFacebook();})])); } 
/// Navigates to the parentHomeScreen when the action is triggered.
onTapImgHome() { Get.toNamed(AppRoutes.parentHomeScreen, ); } 
/// Navigates to the busDetailsScreen when the action is triggered.
onTapImgBus() { Get.toNamed(AppRoutes.busDetailsScreen, ); } 
/// Navigates to the myActivityStudentScreen when the action is triggered.
onTapImgFacebook() { Get.toNamed(AppRoutes.myActivityStudentScreen, ); } 
 }
