import 'controller/sign_in_controller.dart';import 'package:flutter/material.dart';import 'package:thamal_s_application7/core/app_export.dart';import 'package:thamal_s_application7/core/utils/validation_functions.dart';import 'package:thamal_s_application7/widgets/custom_checkbox_button.dart';import 'package:thamal_s_application7/widgets/custom_elevated_button.dart';import 'package:thamal_s_application7/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class SignInScreen extends GetWidget<SignInController> {SignInScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom), child: Form(key: _formKey, child: SizedBox(width: double.maxFinite, child: Column(children: [_buildSignInForm(), Spacer(flex: 51), Text("lbl_sign_in_now".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 40.v), Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: CustomTextFormField(controller: controller.userNameController, hintText: "lbl_username".tr, prefix: Container(margin: EdgeInsets.fromLTRB(14.h, 12.v, 30.h, 12.v), child: CustomImageView(imagePath: ImageConstant.imgLock, height: 16.adaptSize, width: 16.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 40.v), validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;})), SizedBox(height: 10.v), Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: Obx(() => CustomTextFormField(controller: controller.passwordController, hintText: "lbl_password".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, prefix: Container(margin: EdgeInsets.fromLTRB(14.h, 9.v, 30.h, 9.v), child: CustomImageView(imagePath: ImageConstant.imgLocation, height: 21.v, width: 16.h)), prefixConstraints: BoxConstraints(maxHeight: 40.v), suffix: InkWell(onTap: () {controller.isShowPassword.value = !controller.isShowPassword.value;}, child: Container(margin: EdgeInsets.fromLTRB(30.h, 12.v, 7.h, 12.v), child: CustomImageView(imagePath: ImageConstant.imgSettings, height: 15.v, width: 22.h))), suffixConstraints: BoxConstraints(maxHeight: 40.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: controller.isShowPassword.value, contentPadding: EdgeInsets.symmetric(vertical: 11.v)))), SizedBox(height: 14.v), _buildRememberMeSection(), Spacer(flex: 48), CustomElevatedButton(text: "lbl_sign_in".tr, margin: EdgeInsets.symmetric(horizontal: 25.h), onPressed: () {onTapSIGNIN();}), SizedBox(height: 44.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 76.h), child: Text("msg_don_t_you_have_an".tr, style: CustomTextStyles.bodyMediumRegular))), SizedBox(height: 12.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 109.h), child: Text("msg_sign_up_from_here".tr, style: CustomTextStyles.bodyMediumPrimary))), SizedBox(height: 70.v)]))))))); } 
/// Section Widget
Widget _buildSignInForm() { return Container(padding: EdgeInsets.symmetric(horizontal: 130.h, vertical: 25.v), decoration: AppDecoration.outlineOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.customBorderBL150), child: Container(height: 100.adaptSize, width: 100.adaptSize, decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder30), child: CustomImageView(imagePath: ImageConstant.imgWhatsappImage, height: 83.v, width: 100.h, alignment: Alignment.topCenter))); } 
/// Section Widget
Widget _buildRememberMeSection() { return Padding(padding: EdgeInsets.only(left: 25.h, right: 31.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Obx(() => CustomCheckboxButton(text: "lbl_remember_me".tr, value: controller.rememberMe.value, onChange: (value) {controller.rememberMe.value = value;}))), Text("msg_forgot_password".tr, textAlign: TextAlign.center, style: CustomTextStyles.bodySmall11)])); } 
/// Navigates to the studentDashboardScreen when the action is triggered.
onTapSIGNIN() { Get.toNamed(AppRoutes.studentDashboardScreen, ); } 
 }
