import 'controller/sign_in_one_controller.dart';import 'package:flutter/material.dart';import 'package:thamal_s_application7/core/app_export.dart';import 'package:thamal_s_application7/widgets/custom_text_form_field.dart';class SignInOneScreen extends GetWidget<SignInOneController> {const SignInOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildSignInOneStack(), Spacer(flex: 51), Text("lbl_you_are_a".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 18.v), _buildStudentEditText(), SizedBox(height: 11.v), _buildParentEditText(), SizedBox(height: 11.v), _buildAdminEditText(), SizedBox(height: 11.v), _buildBusOwnerEditText(), SizedBox(height: 11.v), _buildBusDriverEditText(), Spacer(flex: 48), Text("msg_already_have_an".tr, style: CustomTextStyles.bodyMediumRegular), SizedBox(height: 13.v), GestureDetector(onTap: () {onTapTxtSignInFromHere();}, child: Text("msg_sign_in_from_here".tr, style: CustomTextStyles.bodyMediumPrimary)), SizedBox(height: 51.v)])))); } 
/// Section Widget
Widget _buildSignInOneStack() { return Container(padding: EdgeInsets.symmetric(horizontal: 130.h, vertical: 25.v), decoration: AppDecoration.outlineOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.customBorderBL150), child: Container(height: 100.adaptSize, width: 100.adaptSize, decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder30), child: CustomImageView(imagePath: ImageConstant.imgWhatsappImage, height: 83.v, width: 100.h, alignment: Alignment.topCenter))); } 
/// Section Widget
Widget _buildStudentEditText() { return Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: CustomTextFormField(controller: controller.studentEditTextController, hintText: "lbl_student".tr, prefix: Container(margin: EdgeInsets.fromLTRB(15.h, 11.v, 29.h, 11.v), child: CustomImageView(imagePath: ImageConstant.imgSettingsOnprimarycontainer, height: 18.v, width: 16.h)), prefixConstraints: BoxConstraints(maxHeight: 40.v))); } 
/// Section Widget
Widget _buildParentEditText() { return Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: CustomTextFormField(controller: controller.parentEditTextController, hintText: "lbl_parent".tr, prefix: Container(margin: EdgeInsets.fromLTRB(11.h, 8.v, 25.h, 8.v), child: CustomImageView(imagePath: ImageConstant.imgAccountoutline, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 40.v))); } 
/// Section Widget
Widget _buildAdminEditText() { return Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: CustomTextFormField(controller: controller.adminEditTextController, hintText: "lbl_admin".tr, prefix: Container(margin: EdgeInsets.fromLTRB(15.h, 10.v, 29.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgLockOnprimarycontainer, height: 18.v, width: 16.h)), prefixConstraints: BoxConstraints(maxHeight: 40.v))); } 
/// Section Widget
Widget _buildBusOwnerEditText() { return Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: CustomTextFormField(controller: controller.busOwnerEditTextController, hintText: "lbl_bus_owner".tr, prefix: Container(margin: EdgeInsets.fromLTRB(11.h, 8.v, 25.h, 8.v), child: CustomImageView(imagePath: ImageConstant.imgAccountoutline, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 40.v))); } 
/// Section Widget
Widget _buildBusDriverEditText() { return Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: CustomTextFormField(controller: controller.busDriverEditTextController, hintText: "lbl_bus_driver".tr, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(11.h, 8.v, 25.h, 8.v), child: CustomImageView(imagePath: ImageConstant.imgAccountoutline, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 40.v))); } 
/// Navigates to the signInScreen when the action is triggered.
onTapTxtSignInFromHere() { Get.toNamed(AppRoutes.signInScreen, ); } 
 }
