import 'controller/student_admin_profile_controller.dart';import 'package:flutter/material.dart';import 'package:thamal_s_application7/core/app_export.dart';import 'package:thamal_s_application7/widgets/app_bar/appbar_leading_image.dart';import 'package:thamal_s_application7/widgets/app_bar/custom_app_bar.dart';class StudentAdminProfileScreen extends GetWidget<StudentAdminProfileController> {const StudentAdminProfileScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 31.v), child: Column(children: [Text("lbl_profile".tr, style: theme.textTheme.titleLarge), SizedBox(height: 28.v), Container(width: 116.h, margin: EdgeInsets.symmetric(horizontal: 108.h), padding: EdgeInsets.symmetric(horizontal: 21.h, vertical: 10.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder58), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 21.v), CustomImageView(imagePath: ImageConstant.imgSettingsBlue800, height: 53.adaptSize, width: 53.adaptSize), SizedBox(height: 6.v), CustomImageView(imagePath: ImageConstant.imgCamera, height: 15.adaptSize, width: 15.adaptSize, alignment: Alignment.centerRight)])), SizedBox(height: 50.v), _buildNameRow(), SizedBox(height: 13.v), _buildNicRow(), SizedBox(height: 13.v), _buildUmisEmailRow(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildLockRow())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 38.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgMegaphone, margin: EdgeInsets.only(left: 20.h, top: 22.v, bottom: 22.v)), actions: [Container(height: 40.adaptSize, width: 40.adaptSize, margin: EdgeInsets.symmetric(horizontal: 10.h, vertical: 8.v), decoration: BoxDecoration(color: appTheme.blueGray100, borderRadius: BorderRadius.circular(20.h)))]); } 
/// Section Widget
Widget _buildNameRow() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_name".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 64.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildNicRow() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_nic".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 74.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildUmisEmailRow() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_umis_email".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 31.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildLockRow() { return Padding(padding: EdgeInsets.only(left: 12.h, right: 12.h, bottom: 10.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgLock, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 2.v, bottom: 6.v)), CustomImageView(imagePath: ImageConstant.imgBellRing, height: 24.adaptSize, width: 24.adaptSize), CustomImageView(imagePath: ImageConstant.imgHome, height: 17.v, width: 20.h, margin: EdgeInsets.only(top: 2.v, bottom: 5.v), onTap: () {onTapImgHome();}), CustomImageView(imagePath: ImageConstant.imgBus, height: 24.adaptSize, width: 24.adaptSize, onTap: () {onTapImgBus();}), CustomImageView(imagePath: ImageConstant.imgFacebook, height: 18.v, width: 22.h, margin: EdgeInsets.only(top: 2.v, bottom: 3.v), onTap: () {onTapImgFacebook();})])); } 
/// Navigates to the studentAdministrationHomeScreen when the action is triggered.
onTapImgHome() { Get.toNamed(AppRoutes.studentAdministrationHomeScreen, ); } 
/// Navigates to the busDetailsScreen when the action is triggered.
onTapImgBus() { Get.toNamed(AppRoutes.busDetailsScreen, ); } 
/// Navigates to the stuAdAnnouncementOneScreen when the action is triggered.
onTapImgFacebook() { Get.toNamed(AppRoutes.stuAdAnnouncementOneScreen, ); } 
 }
