import '../parent_home_screen/widgets/maptextgrid_item_widget.dart';import '../parent_home_screen/widgets/parenthomelist_item_widget.dart';import 'controller/parent_home_controller.dart';import 'models/maptextgrid_item_model.dart';import 'models/parenthomelist_item_model.dart';import 'package:flutter/material.dart';import 'package:thamal_s_application7/core/app_export.dart';import 'package:thamal_s_application7/widgets/app_bar/custom_app_bar.dart';import 'package:thamal_s_application7/widgets/custom_search_view.dart';class ParentHomeScreen extends GetWidget<ParentHomeController> {const ParentHomeScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: SizeUtils.width, height: SizeUtils.height, padding: EdgeInsets.only(top: 56.v), decoration: BoxDecoration(image: DecorationImage(image: AssetImage(ImageConstant.imgGroup430), fit: BoxFit.cover)), child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 5.h, vertical: 11.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [_buildSearchRow(), SizedBox(height: 33.v), _buildMapTextGrid(), SizedBox(height: 88.v), _buildParentHomeList()]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(actions: [Container(height: 40.adaptSize, width: 40.adaptSize, margin: EdgeInsets.symmetric(horizontal: 10.h, vertical: 8.v), decoration: BoxDecoration(color: appTheme.blueGray100, borderRadius: BorderRadius.circular(20.h)))]); } 
/// Section Widget
Widget _buildSearchRow() { return Padding(padding: EdgeInsets.only(left: 5.h, right: 17.h), child: Row(children: [Expanded(child: CustomSearchView(controller: controller.searchController, borderDecoration: SearchViewStyleHelper.fillLightBlueA, fillColor: appTheme.lightBlueA100)), CustomImageView(imagePath: ImageConstant.imgRewindBlue800, height: 17.adaptSize, width: 17.adaptSize, margin: EdgeInsets.only(left: 10.h, top: 9.v, bottom: 8.v))])); } 
/// Section Widget
Widget _buildMapTextGrid() { return Obx(() => GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 247.v, crossAxisCount: 2, mainAxisSpacing: 20.h, crossAxisSpacing: 20.h), physics: NeverScrollableScrollPhysics(), itemCount: controller.parentHomeModelObj.value.maptextgridItemList.value.length, itemBuilder: (context, index) {MaptextgridItemModel model = controller.parentHomeModelObj.value.maptextgridItemList.value[index]; return MaptextgridItemWidget(model, onTapImgMapImage: () {onTapImgMapImage();});})); } 
/// Section Widget
Widget _buildParentHomeList() { return SizedBox(height: 24.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 5.h, right: 7.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 57.h);}, itemCount: controller.parentHomeModelObj.value.parenthomelistItemList.value.length, itemBuilder: (context, index) {ParenthomelistItemModel model = controller.parentHomeModelObj.value.parenthomelistItemList.value[index]; return ParenthomelistItemWidget(model, onTapImgLock: () {onTapImgLock();});}))); } 
/// Navigates to the mapStudentParentScreen when the action is triggered.
onTapImgMapImage() { Get.toNamed(AppRoutes.mapStudentParentScreen); } 
/// Navigates to the parentProfileScreen when the action is triggered.
onTapImgLock() { Get.toNamed(AppRoutes.parentProfileScreen, ); } 
 }
