import 'controller/bus_driver_profile_controller.dart';import 'package:flutter/material.dart';import 'package:thamal_s_application7/core/app_export.dart';import 'package:thamal_s_application7/widgets/app_bar/appbar_leading_image.dart';import 'package:thamal_s_application7/widgets/app_bar/custom_app_bar.dart';class BusDriverProfileScreen extends GetWidget<BusDriverProfileController> {const BusDriverProfileScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 31.v), child: Column(children: [Text("lbl_profile".tr, style: theme.textTheme.titleLarge), SizedBox(height: 28.v), Container(width: 116.h, margin: EdgeInsets.symmetric(horizontal: 108.h), padding: EdgeInsets.symmetric(horizontal: 21.h, vertical: 10.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder58), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 21.v), CustomImageView(imagePath: ImageConstant.imgSettingsBlue800, height: 53.adaptSize, width: 53.adaptSize), SizedBox(height: 6.v), CustomImageView(imagePath: ImageConstant.imgCamera, height: 15.adaptSize, width: 15.adaptSize, alignment: Alignment.centerRight)])), SizedBox(height: 50.v), _buildUserProfile(), SizedBox(height: 13.v), _buildNic(), SizedBox(height: 13.v), _buildEmail(), SizedBox(height: 14.v), _buildMobile(), SizedBox(height: 14.v), _buildHomePhone(), SizedBox(height: 13.v), _buildDateOfBirth(), SizedBox(height: 13.v), _buildAddress(), SizedBox(height: 12.v), _buildDistrict(), SizedBox(height: 11.v), _buildProvince(), SizedBox(height: 15.v), _buildBusId(), SizedBox(height: 36.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 6.h), child: Text("msg_bus_owner_details".tr, style: CustomTextStyles.bodySmall12))), SizedBox(height: 21.v), _buildBusOwnerName(), SizedBox(height: 13.v), _buildBusOwnerId(), SizedBox(height: 15.v), _buildBusId2(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildLock())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 38.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgMegaphone, margin: EdgeInsets.only(left: 20.h, top: 22.v, bottom: 22.v)), actions: [Container(height: 40.adaptSize, width: 40.adaptSize, margin: EdgeInsets.symmetric(horizontal: 10.h, vertical: 8.v), decoration: BoxDecoration(color: appTheme.blueGray100, borderRadius: BorderRadius.circular(20.h)))]); } 
/// Section Widget
Widget _buildUserProfile() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_name".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 64.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildNic() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_nic".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 74.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildEmail() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_email".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 66.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildMobile() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_mobile".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 61.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildHomePhone() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_home_phone".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 31.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildDateOfBirth() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_date_of_birth".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 31.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildAddress() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_address".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 55.h, bottom: 2.v), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildDistrict() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_district".tr, style: theme.textTheme.bodySmall)), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 58.h, bottom: 3.v), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildProvince() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Text("lbl_province".tr, style: theme.textTheme.bodySmall)), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 51.h, bottom: 4.v), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildBusId() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildBusID(busGroupId: "lbl_bus_group_id".tr, busGroupId1: "lbl_bus_group_id".tr), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 30.h, bottom: 2.v), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildBusOwnerName() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_name2".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 64.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildBusOwnerId() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_bus_owner_id".tr, style: theme.textTheme.bodySmall), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 26.h), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildBusId2() { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildBusID(busGroupId: "lbl_bus_group_id".tr, busGroupId1: "lbl_bus_group_id".tr), Container(height: 11.v, width: 230.h, margin: EdgeInsets.only(left: 30.h, bottom: 2.v), decoration: BoxDecoration(color: appTheme.blueGray100))])); } 
/// Section Widget
Widget _buildLock() { return Padding(padding: EdgeInsets.only(left: 12.h, right: 12.h, bottom: 10.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgLock, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 2.v, bottom: 6.v)), CustomImageView(imagePath: ImageConstant.imgBellRing, height: 24.adaptSize, width: 24.adaptSize), CustomImageView(imagePath: ImageConstant.imgHome, height: 17.v, width: 20.h, margin: EdgeInsets.only(top: 2.v, bottom: 5.v), onTap: () {onTapImgHome();}), CustomImageView(imagePath: ImageConstant.imgBus, height: 24.adaptSize, width: 24.adaptSize, onTap: () {onTapImgBus();}), CustomImageView(imagePath: ImageConstant.imgFacebook, height: 18.v, width: 22.h, margin: EdgeInsets.only(top: 2.v, bottom: 3.v), onTap: () {onTapImgFacebook();})])); } 
/// Common widget
Widget _buildBusID({required String busGroupId, required String busGroupId1, }) { return SizedBox(height: 13.v, width: 66.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Text(busGroupId, style: theme.textTheme.bodySmall!.copyWith(color: theme.colorScheme.onPrimaryContainer.withOpacity(1)))), Align(alignment: Alignment.center, child: Text(busGroupId1, style: theme.textTheme.bodySmall!.copyWith(color: theme.colorScheme.onPrimaryContainer.withOpacity(1))))])); } 
/// Navigates to the busDriverHomeScreen when the action is triggered.
onTapImgHome() { Get.toNamed(AppRoutes.busDriverHomeScreen, ); } 
/// Navigates to the busDetailsScreen when the action is triggered.
onTapImgBus() { Get.toNamed(AppRoutes.busDetailsScreen, ); } 
/// Navigates to the routeDetailsScreen when the action is triggered.
onTapImgFacebook() { Get.toNamed(AppRoutes.routeDetailsScreen, ); } 
 }
