import 'controller/my_activity_student_controller.dart';import 'package:calendar_date_picker2/calendar_date_picker2.dart';import 'package:flutter/material.dart';import 'package:thamal_s_application7/core/app_export.dart';class MyActivityStudentScreen extends GetWidget<MyActivityStudentController> {const MyActivityStudentScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 39.h, vertical: 36.v), child: Column(children: [Text("lbl_november".tr, style: CustomTextStyles.bodyMediumRoboto), SizedBox(height: 9.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 11.h, right: 135.h), child: Row(children: [Padding(padding: EdgeInsets.symmetric(vertical: 6.v), child: Text("lbl_1".tr, style: CustomTextStyles.bodyMediumRobotoOnPrimaryRegular)), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 6.v), child: Text("lbl_1".tr, style: CustomTextStyles.bodyMediumRobotoOnPrimaryRegular)), Container(width: 30.adaptSize, margin: EdgeInsets.only(left: 23.h), padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 6.v), decoration: AppDecoration.fillBlue.copyWith(borderRadius: BorderRadiusStyle.circleBorder15), child: Text("lbl_1".tr, style: CustomTextStyles.bodyMediumRobotoWhiteA700)), Padding(padding: EdgeInsets.only(left: 12.h, bottom: 13.v), child: Text("lbl_sun".tr.toUpperCase(), style: CustomTextStyles.bodySmallRobotoGray600))]))), SizedBox(height: 30.v), Text("lbl_november".tr, style: CustomTextStyles.bodyMediumRoboto), SizedBox(height: 23.v), _buildCalendar(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildLock())); } 
/// Section Widget
Widget _buildCalendar() { return Obx(() => SizedBox(height: 263.v, width: 282.h, child: CalendarDatePicker2(config: CalendarDatePicker2Config(calendarType: CalendarDatePicker2Type.range, rangeBidirectional: true, firstDate: DateTime(DateTime.now().year - 5), lastDate: DateTime(DateTime.now().year + 5), selectedDayHighlightColor: Color(0XFFFFFFFF), firstDayOfWeek: 0, weekdayLabelTextStyle: TextStyle(color: appTheme.gray600, fontFamily: 'Roboto', fontWeight: FontWeight.w400), selectedDayTextStyle: TextStyle(color: Color(0XFF252C33), fontFamily: 'Roboto', fontWeight: FontWeight.w400), disabledDayTextStyle: TextStyle(color: theme.colorScheme.onPrimary, fontFamily: 'Roboto', fontWeight: FontWeight.w400), weekdayLabels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]), value: controller.selectedDatesFromCalendar1.value, onValueChanged: (dates) {controller.selectedDatesFromCalendar1.value = dates;}))); } 
/// Section Widget
Widget _buildLock() { return Padding(padding: EdgeInsets.only(left: 12.h, right: 12.h, bottom: 10.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 2.v, bottom: 6.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgLock, height: 16.adaptSize, width: 16.adaptSize, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgLock, height: 16.adaptSize, width: 16.adaptSize, alignment: Alignment.center)])), _buildStackRow(busImage1: ImageConstant.imgBellRing, busImage2: ImageConstant.imgBellRing), Container(height: 17.v, width: 20.h, margin: EdgeInsets.only(top: 2.v, bottom: 5.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgHome, height: 17.v, width: 20.h, alignment: Alignment.center, onTap: () {onTapImgHome();}), CustomImageView(imagePath: ImageConstant.imgHome, height: 17.v, width: 20.h, alignment: Alignment.center)])), _buildStackRow(busImage1: ImageConstant.imgBus, busImage2: ImageConstant.imgBus), Container(height: 18.v, width: 22.h, margin: EdgeInsets.only(top: 2.v, bottom: 3.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgFacebook, height: 18.v, width: 22.h, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgFacebook, height: 18.v, width: 22.h, alignment: Alignment.center)]))])); } 
/// Common widget
Widget _buildStackRow({required String busImage1, required String busImage2, }) { return SizedBox(height: 24.adaptSize, width: 24.adaptSize, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: busImage1, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center), CustomImageView(imagePath: busImage2, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center)])); } 
/// Navigates to the studentProfileScreen when the action is triggered.
onTapImgHome() { Get.toNamed(AppRoutes.studentProfileScreen, ); } 
 }
